### ISSUE TITLE
Invalid value for <polygon> attribute points...

### ISSUE THREAD

**Issue by azevedo-252** [adobe-webplatform/Snap.svg#373] opened 2015-04-28 18:23 UTC
It seems the newest version 0.4.1 doesn't allow to animate a polygon's "points" attribute.

```
var s = Snap(400, 620);
var pol = s.polygon([0, 464, 0, 464, 111.6, 464, 282.5, 464, 457.4, 464, 613.4, 464, 762.3, 464, 912.3, 464, 1440.1, 464, 0, 464]);
pol.animate(
  { points: [0, 464, 0, 367, 111.6, 323.3, 282.5, 373, 457.4, 423.8, 613.4, 464, 762.3, 464, 912.3, 464, 1440.1, 464, 0, 464] },
  1000)
```

It errors with 'Error: Invalid value for <polygon> attribute points="0"'

I got it working with version 0.3.0. So some change must have broken this behavior

**Comment by maercky** [comment] 2015-05-19 14:21
The fix you provided works! Thanks!

**Comment by thiberaw** [comment] 2015-06-15 13:43
Yep, Thank you https://github.com/ThomasBrierley

**Comment by darklow** [comment] 2015-08-05 09:36
+1. Thanks
Any chance related PR will be accepted?

**Comment by c0d3rman** [comment] 2015-11-10 00:52
Bump. Please either accept the PR or implement your own fix.

**Comment by vamp** [comment] 2015-12-24 11:22
any updates?

**Comment by danielpanc** [comment] 2016-01-20 14:48
i am waiting for this update too

**Comment by irthos** [comment] 2016-01-24 07:06
+1 the struggle is real

**Comment by ibrierley** [comment] 2016-01-25 12:17
Btw, I was just answering a question on this error on Stackoverflow which I think is probably related http://stackoverflow.com/questions/34991254/animate-polygon-points-snap-svg , you can get around it I think just by using a default Animation, rather than an element animation. So it would look something like this....


    Snap.animate( myStartingPointsArray, myEndingPointsArray, 
        function( val ){ 
          myPolygon.attr({ points: val })
        }, 
      2000)

or a plugin....

    Snap.plugin( function( Snap, Element, Paper, global ) {
       Element.prototype.polyAnimate = function( destPoints, duration, easing, callback ) {
       var poly = this;
        Snap.animate( this.attr('points'), destPoints,  
           function( val ){ poly.attr({ points: val }) }, duration, easing, callback)
        };
    });

**Comment by ThomasBrierley** [comment] 2016-01-26 15:03
Another forward compatible workaround is to use v0.3.0 until this fix is released (provided you are not depending on any features in ~v0.4.0). As both #373 and #378 are regressions that were introduced between v0.3.0 and v0.4.0

I've been locking all my work to this version since last may without any issues other than the memory leak.

**Comment by ibrierley** [comment] 2016-01-26 15:20
Just thinking, as I don't know git well...

Would it make sense to fork Snap into a patched version just of important updates (eg a temp 0.4.1 if you like) until Dmitry gets chance to include important fixes. Main ones I'm aware of are this, and the memory fix.

Not sure if this is feasible (or against t&c's?) or advisable as not so familiar with git or if it would get really messy, but I'd try and help if possible.

**Comment by ThomasBrierley** [comment] 2016-01-26 17:29
It's not so much a question of if it's possible: we can fork/modify because it's a public git repo and are legally free to because it's licensed with Apache 2.0. The problem is any forks will not be recognised as "official" (think npm and bower registries) which may defeat the purpose of making a patched fork.

Anyone can fork and merge all the un-merged PRs and build it if they want, the problem with suggesting that others use it is the obligation for that fork to be maintained in the future (even if that just means don't delete it from your account). For instance this build is a collection of my patches on my fork:

https://github.com/ThomasBrierley/Snap.svg/releases/tag/memory-leak-fix

However this is for my own purposes and I intend to delete the entire fork as soon as the official Snap repo integrates it... if anyone points their packages.json or whatever to that repo then it will break in the future. That said, a persistent community fork under a different name will inevitably happen if necessary... time waits for no man and all that.

**Comment by ThomasBrierley** [comment] 2016-01-26 18:51
Sorry to reply to my own post, but just to clarify:

Feel free to fetch/fork/clone my link above and include it in your own project or host it yourself. My point in response to @ibrierley is that it should be made clear to anyone using these temporary types of builds (by me or anyone else) not to use them with package managers like npm/bower etc to pull them in... I should have just said that instead... :no_mouth:

**Comment by ibrierley** [comment] 2016-01-26 19:04
Yes of course, hadn't even thought about that angle, thanks.

**Comment by midweststudios** [comment] 2016-05-09 18:58
The issue still hasn't been fixed in the master branch- but I downloaded your update linked above and it fixed my problem with animating polylines. Thank you!

**Comment by margaretmoser** [comment] 2016-05-31 00:05
One more in favor of accepting this PR. This is one of the features that sets snap apart from other svg libraries... but it's broken out of the box.

**Comment by mgan59** [comment] 2016-06-03 22:57
been learning snapsvg and just spent 2 hours banging my head on the wall with this issue to only uncover it from a stackoverflow comment all the way at the bottom.  -- http://stackoverflow.com/questions/29732802/animating-points-in-a-polygon-with-snap-svg?rq=1


can we escalate this pr merge, truly pain for those coming to svg and trying to learn and out of the box this is an issue.

**Comment by mrandt** [comment] 2016-07-04 19:37
+1 for fixing this; the bug is annoying and I just found this thread by accident after wasting much time trying to find out why it was not working.

**Comment by OpticNectar** [comment] 2016-09-30 16:33
This ever getting fixed?

**Comment by Sewdn** [comment] 2016-11-02 08:27
Hi, first of all: thanks for this great library.
Bu as mentioned by several people in the past year and a half: this issue is breaking an important feature of snapsvg. A pull request was filed, this shouldn't take long to revise and merge.

A polite callout to the maintainers of this valuable library: could you please review? Thanks a lot!
@DmitryBaranovskiy

**Comment by Takkster** [comment] 2016-11-07 13:08
+1 
I need this aswell.

**Comment by ThomasBrierley** [comment] 2017-01-04 11:02
Should be ok to close this now, didn't autoclose for some reason.

Fix has been merged and was well tested before.

**Closed** 2017-01-06 11:57 UTC
