### ISSUE TITLE
Element.transform() breaks if given a parameter in scientific notation

### ISSUE THREAD

**Issue by Stickerpants** [adobe-webplatform/Snap.svg#497] opened 2017-01-19 02:19 UTC
Suppose we have an element `o`. If we call `o.transform("s0.5 t2e-11")`, this is processed with a translation of `(2, -11)` instead of the expected `(2e-11, 0)`.

More details on this [can be found here](http://stickerpants.tumblr.com/post/156061395110/the-mystery-of-the-bouncing-square).

If scientific notation isn't supported in these strings, then I don't consider this a bug - but I do think it's worth stating somewhere.

**Comment by ThomasBrierley** [comment] 2017-01-19 10:29
Hi @Stickerpants 

This is a duplicate of #378

The fix has just been merged, next release will be fixed.

**Comment by ThomasBrierley** [comment] 2017-02-06 18:42
This can be closed

**Closed** 2017-02-10 11:00 UTC
